language: perl6

perl6:
  - latest

os:
  - linux

before_install:
   - wget https://sourceforge.net/projects/freestdf/files/libstdf/libstdf-0.4.tar.bz2
   - bunzip2 libstdf-0.4.tar.bz2
   - tar -xvf libstdf-0.4.tar
   - cd libstdf-0.4
   - ./configure --disable-warn-untested
   - make
   - sudo make install
   - sudo ldconfig
   - cd ..

install:
   - rakudobrew build-zef
   - zef install .
